// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC20XwLDOSNphCqN1Wk5ypoRoZ2pGecmuo',
    appId: '1:1094877603105:web:539d40c370350969508a60',
    messagingSenderId: '1094877603105',
    projectId: 'resepkita-apps',
    authDomain: 'resepkita-apps.firebaseapp.com',
    databaseURL: 'https://resepkita-apps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resepkita-apps.firebasestorage.app',
    measurementId: 'G-TWKL2Q7FR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJkEGFf9S0BnqkDW7NAxRSkPa_cAUDmMs',
    appId: '1:1094877603105:android:4d7a59d3a02ec6bf508a60',
    messagingSenderId: '1094877603105',
    projectId: 'resepkita-apps',
    databaseURL: 'https://resepkita-apps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resepkita-apps.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC20XwLDOSNphCqN1Wk5ypoRoZ2pGecmuo',
    appId: '1:1094877603105:web:539d40c370350969508a60',
    messagingSenderId: '1094877603105',
    projectId: 'resepkita-apps',
    authDomain: 'resepkita-apps.firebaseapp.com',
    databaseURL: 'https://resepkita-apps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resepkita-apps.firebasestorage.app',
    measurementId: 'G-TWKL2Q7FR4',
  );

}