name: ujicoba_resepkita
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.7
  provider: ^6.1.5
  flutter_local_notifications: ^19.2.0
  share_plus: ^11.0.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
